apiVersion: v1
kind: Pod
metadata: 
  name: redis-app-prod
  labels:
    name: redis-prod
    app: demo-voting-app
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379