apiVersion: v1
kind: Pod
metadata: 
  name: result-app-prod
  labels:
    name: result-prod
    app: demo-voting-app
spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80